name: Django Project Action

on:
  push:
    branches:
      - master  # You can specify the branch you want to trigger the action

jobs:
  run_django_tests:
    runs-on: ubuntu-latest  # You can change the operating system as needed

    steps:
    - name: Checkout code
      uses: actions/checkout@v2  # This step checks out your repository's code

    - name: Set up Python
      uses: actions/setup-python@v2  # This step sets up Python environment
      with:
        python-version: '3.x'  # You can specify the Python version you need

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt  # Install your project dependencies if needed

    - name: Set up Django
      run: |
        python manage.py migrate  # Apply migrations if needed
        python manage.py collectstatic --noinput  # Collect static files if needed

    - name: Run Django tests
      run: python manage.py test  # Run Django tests
